CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE oauth2_registered_client (
    id varchar(100) NOT NULL,
    client_id varchar(100) NOT NULL,
    client_id_issued_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret varchar(200) DEFAULT NULL,
    client_secret_expires_at timestamp DEFAULT NULL,
    client_name varchar(200) NOT NULL,
    client_authentication_methods varchar(1000) NOT NULL,
    authorization_grant_types varchar(1000) NOT NULL,
    redirect_uris varchar(1000) DEFAULT NULL,
    post_logout_redirect_uris varchar(1000) DEFAULT NULL,
    scopes varchar(1000) NOT NULL,
    client_settings varchar(2000) NOT NULL,
    token_settings varchar(2000) NOT NULL
);

CREATE TABLE oauth2_authorization (
    id varchar(100) NOT NULL,
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorization_grant_type varchar(100) NOT NULL,
    authorized_scopes varchar(1000) DEFAULT NULL,
    attributes text DEFAULT NULL,
    state varchar(500) DEFAULT NULL,
    authorization_code_value text DEFAULT NULL,
    authorization_code_issued_at timestamp DEFAULT NULL,
    authorization_code_expires_at timestamp DEFAULT NULL,
    authorization_code_metadata text DEFAULT NULL,
    access_token_value text DEFAULT NULL,
    access_token_issued_at timestamp DEFAULT NULL,
    access_token_expires_at timestamp DEFAULT NULL,
    access_token_metadata text DEFAULT NULL,
    access_token_type varchar(100) DEFAULT NULL,
    access_token_scopes varchar(1000) DEFAULT NULL,
    oidc_id_token_value text DEFAULT NULL,
    oidc_id_token_issued_at timestamp DEFAULT NULL,
    oidc_id_token_expires_at timestamp DEFAULT NULL,
    oidc_id_token_metadata text DEFAULT NULL,
    refresh_token_value text DEFAULT NULL,
    refresh_token_issued_at timestamp DEFAULT NULL,
    refresh_token_expires_at timestamp DEFAULT NULL,
    refresh_token_metadata text DEFAULT NULL,
    user_code_value text DEFAULT NULL,
    user_code_issued_at timestamp DEFAULT NULL,
    user_code_expires_at timestamp DEFAULT NULL,
    user_code_metadata text DEFAULT NULL,
    device_code_value text DEFAULT NULL,
    device_code_issued_at timestamp DEFAULT NULL,
    device_code_expires_at timestamp DEFAULT NULL,
    device_code_metadata text DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE oauth2_authorization_consent (
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorities varchar(1000) NOT NULL,
    PRIMARY KEY (registered_client_id, principal_name)
);

ALTER TABLE oauth2_registered_client ADD CONSTRAINT uq_oauth2_registered_client_id_client UNIQUE (client_id);

CREATE TABLE roles (
                       id_role integer generated by DEFAULT as identity PRIMARY KEY,
                       name varchar(50) UNIQUE,
                       description varchar(25)
);

CREATE TABLE users (
                       id_user       uuid                     DEFAULT uuid_generate_v4() NOT NULL PRIMARY KEY,
                       email         text                                                NOT NULL UNIQUE,
                       full_name     text                                                NOT NULL,
                       user_name     varchar(25) UNIQUE,
                       password_hash text                                                NOT NULL,
                       created_at    timestamp with time zone DEFAULT now(),
                       updated_at    timestamp with time zone DEFAULT now(),
                       is_active     boolean                  DEFAULT true,
                       last_login    timestamp with time zone,
                       phone         varchar(10),
                       fist_login    boolean                  DEFAULT true
);

CREATE TABLE user_role_client (
                                  id_user   uuid    NOT NULL references users (id_user),
                                  id_role   integer NOT NULL references roles (id_role),
                                  client_id varchar NOT NULL references oauth2_registered_client (client_id),
                                  PRIMARY KEY (id_user, id_role, client_id)
);

CREATE INDEX idx_user_role_client_user ON user_role_client (id_user);
CREATE INDEX idx_user_role_client_client ON user_role_client (client_id);

ALTER TABLE roles
    ALTER COLUMN description TYPE varchar(100)

